[project]
name = "topk"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "", email = ""},
]
dependencies = [
    "tqdm>=4.66.5",
    "torch>=2.4.1",
    "nnsight>=0.3.6",
    "datasets==2.17.1",
    "wandb>=0.18.3",
    "ipykernel>=6.29.5",
    "plotly>=5.24.1",
    "transformer-lens>=2.8.1",
    "sae-lens @ https://github.com/jbloomAus/SAELens/releases/download/v4.3.3/sae_lens-4.3.3-py3-none-any.whl",
    "nbformat>=5.10.4",
    "sae-dashboard>=0.6.4",
    "seaborn>=0.13.2",
    "umap>=0.1.1",
    "notebook>=7.2.2",
    "sae-vis>=0.2.15",
    "datashader>=0.16.3",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[[tool.pdm.source]]
name = "private"
url = "https://download.pytorch.org/whl/cu124"
include_packages = ["torch"]
exclude_packages = ["*"]